mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat" Z:\DayZ\Modding\iat\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_corrosive_biogas" Z:\DayZ\Modding\iat_corrosive_biogas\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_enhanced_bioprotection" Z:\DayZ\Modding\iat_enhanced_bioprotection\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_facepaints" Z:\DayZ\Modding\iat_facepaints\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_infinity_gauntlet" Z:\DayZ\Modding\iat_infinity_gauntlet\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_literary_devices" Z:\DayZ\Modding\iat_literary_devices\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_map_border_teleport" Z:\DayZ\Modding\iat_map_border_teleport\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_notes_enhanced" Z:\DayZ\Modding\iat_notes_enhanced\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_retextures" Z:\DayZ\Modding\iat_retextures\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_roleplay_emotes" Z:\DayZ\Modding\iat_roleplay_emotes\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_simple_territories" Z:\DayZ\Modding\iat_simple_territories\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_structures" Z:\DayZ\Modding\iat_structures\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_universal_repair" Z:\DayZ\Modding\iat_universal_repair\addons
mklink /J "Y:\SteamLibrary\steamapps\common\DayZ\iat_weapon_quickbar" Z:\DayZ\Modding\iat_weapon_quickbar\addons