mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat" Z:\DayZ\Modding\iat\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_codelock" Z:\DayZ\Modding\iat_codelock\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_collectibles" Z:\DayZ\Modding\iat_collectibles\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_corrosive_biogas" Z:\DayZ\Modding\iat_corrosive_biogas\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_crafting_plus" Z:\DayZ\Modding\iat_crafting_plus\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_display_case" Z:\DayZ\Modding\iat_display_case\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_double_armbands" Z:\DayZ\Modding\iat_double_armbands\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_dynamic_radio_range" Z:\DayZ\Modding\iat_dynamic_radio_range\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_dynamic_traps" Z:\DayZ\Modding\iat_dynamic_traps\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_enhanced_bioprotection" Z:\DayZ\Modding\iat_enhanced_bioprotection\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_facepaints" Z:\DayZ\Modding\iat_facepaints\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_infinity_gauntlet" Z:\DayZ\Modding\iat_infinity_gauntlet\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_literary_devices" Z:\DayZ\Modding\iat_literary_devices\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_map_border_teleport" Z:\DayZ\Modding\iat_map_border_teleport\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_melee_weapons" Z:\DayZ\Modding\iat_melee_weapons\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_mining_enhanced" Z:\DayZ\Modding\iat_mining_enhanced\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_molotov_firegrenades" Z:\DayZ\Modding\iat_molotov_firegrenades\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_more_doors" Z:\DayZ\Modding\iat_more_doors\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_notes_enhanced" Z:\DayZ\Modding\iat_notes_enhanced\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_powered_radio_towers" Z:\DayZ\Modding\iat_powered_radio_towers\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_prop_items" Z:\DayZ\Modding\iat_prop_items\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_radio_mute" Z:\DayZ\Modding\iat_radio_mute\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_retextures" Z:\DayZ\Modding\iat_retextures\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_roleplay_emotes" Z:\DayZ\Modding\iat_roleplay_emotes\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_roll_tables" Z:\DayZ\Modding\iat_roll_tables\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_simple_carpentry" Z:\DayZ\Modding\iat_simple_carpentry\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_simple_territories" Z:\DayZ\Modding\iat_simple_territories\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_single_item_split" Z:\DayZ\Modding\iat_single_item_split\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_smelting_metallurgy" Z:\DayZ\Modding\iat_smelting_metallurgy\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_smoke_signals" Z:\DayZ\Modding\iat_smoke_signals\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_soft_surrender" Z:\DayZ\Modding\iat_soft_surrender\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_structures" Z:\DayZ\Modding\iat_structures\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_teleport_linker" Z:\DayZ\Modding\iat_teleport_linker\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_treasure_hunts" Z:\DayZ\Modding\iat_treasure_hunts\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_universal_repair" Z:\DayZ\Modding\iat_universal_repair\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_universal_dye" Z:\DayZ\Modding\iat_universal_dye\addons
mklink /J "C:\Users\Tree\Documents\DayZ Projects\iat_weapon_quickbar" Z:\DayZ\Modding\iat_weapon_quickbar\addons