// auto generated file
class IAT_FacePaintOptions
{
	protected static ref map<string, ref array<string>> s_FacePaintOptionsMap;

	void IAT_FacePaintOptions()
	{
		// create the map
		if (!s_FacePaintOptionsMap)
			s_FacePaintOptionsMap = new ref map<string, ref array<string>>;
		// call autogenerated
		AutoGeneratedInit();
	}

	static TStringArray GetCategories()
	{
		return s_FacePaintOptionsMap.GetKeyArray();
	}

	static TStringArray GetCategoryItems(string category)
	{
		if (s_FacePaintOptionsMap.Contains(category))
		{
			return s_FacePaintOptionsMap.Get(category);
		}
		return {};
	}

	protected void AutoGeneratedInit(){}
};