// auto generated file
class IAT_FacePaintOptions
{
	protected static ref map<string, ref array<string>> s_FacePaintOptionsMap;

	void IAT_FacePaintOptions()
	{
		// create the map
		if (!s_FacePaintOptionsMap)
			s_FacePaintOptionsMap = new map<string, ref array<string>>;
		// call autogenerated
		AutoGeneratedInit();
	}

	TStringArray GetCategories()
	{
		return s_FacePaintOptionsMap.GetKeyArray();
	}

	TStringArray GetCategoryItems(string category)
	{
		if (s_FacePaintOptionsMap.Contains(category))
		{
			return s_FacePaintOptionsMap.Get(category);
		}
		return {};
	}
	void PrettyPrint()
	{
		Print("--[FACE PAINT OPTIONS BEGIN]");
		TStringArray paintKeys = GetCategories();
		TStringArray paintItems;
		foreach (string paintKey : paintKeys)
		{
			PrintFormat("----Paint Category: %1", paintKey);
			paintItems = s_FacePaintOptionsMap.Get(paintKey);
			foreach(string paintItem : paintItems)
			{
				PrintFormat("------Paint Item: %1", paintItem);
			}
		}
		Print("--[END]");
	}

	protected void AutoGeneratedInit(){}

};