// auto generated file
class IAT_FacePaintOptions
{
	protected static ref map<string, ref array<string>> s_FacePaintOptionsMap;

	void IAT_FacePaintOptions()
	{
		// create the map
		if (!s_FacePaintOptionsMap)
			s_FacePaintOptionsMap = new ref map<string, ref array<string>>;
		// call autogenerated
		AutoGeneratedInit();
	}

	static TStringArray GetCategories()
	{
		return s_FacePaintOptionsMap.GetKeyArray();
	}

	static TStringArray GetCategoryItems(string category)
	{
		if (s_FacePaintOptionsMap.Contains(category))
		{
			return s_FacePaintOptionsMap.Get(category);
		}
		return {};
	}

	protected void AutoGeneratedInit()
	{
		array<string> category0_options = new ref array<string>;
		category0_options.Insert("bosnia");
		category0_options.Insert("bulgaria1");
		category0_options.Insert("bulgaria2");
		category0_options.Insert("croatia");
		category0_options.Insert("czech1");
		category0_options.Insert("czech2");
		category0_options.Insert("desert");
		category0_options.Insert("digital");
		category0_options.Insert("digitalblue");
		category0_options.Insert("dragonscale");
		category0_options.Insert("dragonscalered");
		category0_options.Insert("france");
		category0_options.Insert("germany");
		category0_options.Insert("hungary1");
		category0_options.Insert("hungary2");
		category0_options.Insert("macedonia");
		category0_options.Insert("olive");
		category0_options.Insert("poland1");
		category0_options.Insert("poland2");
		category0_options.Insert("romania1");
		category0_options.Insert("romania2");
		category0_options.Insert("slovenia");
		category0_options.Insert("uk");
		category0_options.Insert("usa");
		category0_options.Insert("woodland");
		category0_options.Insert("woodlandgreen");
		category0_options.Insert("woodlandm81");
		category0_options.Insert("woodlandred");
		category0_options.Insert("woodlandwinter");
		category0_options.Insert("yugoslavia");
		s_FacePaintOptionsMap.Insert("camo", category0_options);

		array<string> category1_options = new ref array<string>;
		category1_options.Insert("argentina");
		category1_options.Insert("austria");
		category1_options.Insert("belgium");
		category1_options.Insert("brazil");
		category1_options.Insert("canada");
		category1_options.Insert("chile");
		category1_options.Insert("colombia");
		category1_options.Insert("croatia");
		category1_options.Insert("czechia");
		category1_options.Insert("denmark");
		category1_options.Insert("england");
		category1_options.Insert("france");
		category1_options.Insert("germany");
		category1_options.Insert("hungary");
		category1_options.Insert("italy");
		category1_options.Insert("japan");
		category1_options.Insert("mexico");
		category1_options.Insert("netherlands");
		category1_options.Insert("nigeria");
		category1_options.Insert("paraguay");
		category1_options.Insert("poland");
		category1_options.Insert("portugal");
		category1_options.Insert("romania");
		category1_options.Insert("russia");
		category1_options.Insert("scottland");
		category1_options.Insert("serbia");
		category1_options.Insert("south_korea");
		category1_options.Insert("spain");
		category1_options.Insert("sweden");
		category1_options.Insert("switzerland");
		category1_options.Insert("ukraine");
		category1_options.Insert("uruguay");
		category1_options.Insert("usa");
		s_FacePaintOptionsMap.Insert("flags", category1_options);

		array<string> category2_options = new ref array<string>;
		category2_options.Insert("catman");
		category2_options.Insert("clown1");
		category2_options.Insert("demon");
		category2_options.Insert("geisha1");
		category2_options.Insert("geisha_traditional");
		category2_options.Insert("glowstick_blue");
		category2_options.Insert("glowstick_green");
		category2_options.Insert("glowstick_red");
		category2_options.Insert("glowstick_white");
		category2_options.Insert("glowstick_yellow");
		category2_options.Insert("skullface");
		category2_options.Insert("spaceman");
		category2_options.Insert("starchild");
		category2_options.Insert("tattoo_teardrop");
		s_FacePaintOptionsMap.Insert("masks_&_tattoos", category2_options);

		array<string> category3_options = new ref array<string>;
		category3_options.Insert("left_cheek_bruise");
		category3_options.Insert("left_cheek_scar");
		category3_options.Insert("left_eye_bearclaw");
		category3_options.Insert("left_eye_bearclaw_faded");
		category3_options.Insert("left_eye_bearclaw_recent");
		category3_options.Insert("left_eyeb_ruise");
		category3_options.Insert("right_cheek_scar");
		category3_options.Insert("right_keloid");
		category3_options.Insert("right_longscar");
		s_FacePaintOptionsMap.Insert("scars", category3_options);

	}

};