name = "iat_retextures"
author = "ItsATreee"
prefix = "iat_retextures"
mainprefix = "P"

[version]
path = "release_version.hpp"
git_hash = 0

[hemtt.release]
archive = true

[signing]
authority = "ItsATreeev2"