class IAT_TarotCardDeck_Colorbase extends ItemBase
{
	//Debug menu Spawn Ground Special
	override void OnDebugSpawn()
	{
		GameInventory inventory = GetInventory();
		inventory.CreateAttachment("IAT_TarotCard_1w");
		inventory.CreateAttachment("IAT_TarotCard_2w");
		inventory.CreateAttachment("IAT_TarotCard_3w");
		inventory.CreateAttachment("IAT_TarotCard_4w");
		inventory.CreateAttachment("IAT_TarotCard_5w");
		inventory.CreateAttachment("IAT_TarotCard_6w");
		inventory.CreateAttachment("IAT_TarotCard_7w");
		inventory.CreateAttachment("IAT_TarotCard_8w");
		inventory.CreateAttachment("IAT_TarotCard_9w");
		inventory.CreateAttachment("IAT_TarotCard_10w");
		inventory.CreateAttachment("IAT_TarotCard_11w");
		inventory.CreateAttachment("IAT_TarotCard_12w");
		inventory.CreateAttachment("IAT_TarotCard_13w");
		inventory.CreateAttachment("IAT_TarotCard_14w");
		inventory.CreateAttachment("IAT_TarotCard_1c");
		inventory.CreateAttachment("IAT_TarotCard_2c");
		inventory.CreateAttachment("IAT_TarotCard_3c");
		inventory.CreateAttachment("IAT_TarotCard_4c");
		inventory.CreateAttachment("IAT_TarotCard_5c");
		inventory.CreateAttachment("IAT_TarotCard_6c");
		inventory.CreateAttachment("IAT_TarotCard_7c");
		inventory.CreateAttachment("IAT_TarotCard_8c");
		inventory.CreateAttachment("IAT_TarotCard_9c");
		inventory.CreateAttachment("IAT_TarotCard_10c");
		inventory.CreateAttachment("IAT_TarotCard_11c");
		inventory.CreateAttachment("IAT_TarotCard_12c");
		inventory.CreateAttachment("IAT_TarotCard_13c");
		inventory.CreateAttachment("IAT_TarotCard_14c");
		inventory.CreateAttachment("IAT_TarotCard_1s");
		inventory.CreateAttachment("IAT_TarotCard_2s");
		inventory.CreateAttachment("IAT_TarotCard_3s");
		inventory.CreateAttachment("IAT_TarotCard_4s");
		inventory.CreateAttachment("IAT_TarotCard_5s");
		inventory.CreateAttachment("IAT_TarotCard_6s");
		inventory.CreateAttachment("IAT_TarotCard_7s");
		inventory.CreateAttachment("IAT_TarotCard_8s");
		inventory.CreateAttachment("IAT_TarotCard_9s");
		inventory.CreateAttachment("IAT_TarotCard_10s");
		inventory.CreateAttachment("IAT_TarotCard_11s");
		inventory.CreateAttachment("IAT_TarotCard_12s");
		inventory.CreateAttachment("IAT_TarotCard_13s");
		inventory.CreateAttachment("IAT_TarotCard_14s");
		inventory.CreateAttachment("IAT_TarotCard_1p");
		inventory.CreateAttachment("IAT_TarotCard_2p");
		inventory.CreateAttachment("IAT_TarotCard_3p");
		inventory.CreateAttachment("IAT_TarotCard_4p");
		inventory.CreateAttachment("IAT_TarotCard_5p");
		inventory.CreateAttachment("IAT_TarotCard_6p");
		inventory.CreateAttachment("IAT_TarotCard_7p");
		inventory.CreateAttachment("IAT_TarotCard_8p");
		inventory.CreateAttachment("IAT_TarotCard_9p");
		inventory.CreateAttachment("IAT_TarotCard_10p");
		inventory.CreateAttachment("IAT_TarotCard_11p");
		inventory.CreateAttachment("IAT_TarotCard_12p");
		inventory.CreateAttachment("IAT_TarotCard_13p");
		inventory.CreateAttachment("IAT_TarotCard_14p");
		inventory.CreateAttachment("IAT_TarotCard_1ma");
		inventory.CreateAttachment("IAT_TarotCard_2ma");
		inventory.CreateAttachment("IAT_TarotCard_3ma");
		inventory.CreateAttachment("IAT_TarotCard_4ma");
		inventory.CreateAttachment("IAT_TarotCard_5ma");
		inventory.CreateAttachment("IAT_TarotCard_6ma");
		inventory.CreateAttachment("IAT_TarotCard_7ma");
		inventory.CreateAttachment("IAT_TarotCard_8ma");
		inventory.CreateAttachment("IAT_TarotCard_9ma");
		inventory.CreateAttachment("IAT_TarotCard_10ma");
		inventory.CreateAttachment("IAT_TarotCard_11ma");
		inventory.CreateAttachment("IAT_TarotCard_12ma");
		inventory.CreateAttachment("IAT_TarotCard_13ma");
		inventory.CreateAttachment("IAT_TarotCard_14ma");
		inventory.CreateAttachment("IAT_TarotCard_15ma");
		inventory.CreateAttachment("IAT_TarotCard_16ma");
		inventory.CreateAttachment("IAT_TarotCard_17ma");
		inventory.CreateAttachment("IAT_TarotCard_18ma");
		inventory.CreateAttachment("IAT_TarotCard_19ma");
		inventory.CreateAttachment("IAT_TarotCard_20ma");
		inventory.CreateAttachment("IAT_TarotCard_21ma");
		inventory.CreateAttachment("IAT_TarotCard_22ma");
	}
};
class IAT_TarotCardDeck_Basic extends IAT_TarotCardDeck_Colorbase{};
class IAT_TarotCardDeck_essesentiendum extends IAT_TarotCardDeck_Colorbase{};

class IAT_TarotCard_Colorbase extends ItemBase{};

class IAT_TarotCard_1w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_2w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_3w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_4w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_5w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_6w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_7w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_8w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_9w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_10w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_11w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_12w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_13w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_14w extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_1c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_2c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_3c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_4c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_5c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_6c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_7c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_8c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_9c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_10c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_11c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_12c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_13c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_14c extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_1s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_2s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_3s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_4s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_5s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_6s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_7s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_8s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_9s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_10s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_11s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_12s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_13s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_14s extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_1p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_2p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_3p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_4p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_5p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_6p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_7p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_8p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_9p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_10p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_11p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_12p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_13p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_14p extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_1ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_2ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_3ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_4ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_5ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_6ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_7ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_8ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_9ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_10ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_11ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_12ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_13ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_14ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_15ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_16ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_17ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_18ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_19ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_20ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_21ma extends IAT_TarotCard_Colorbase{};
class IAT_TarotCard_22ma extends IAT_TarotCard_Colorbase{};