class IAT_CardDeck_Colorbase extends ItemBase
{
	//Debug menu Spawn Ground Special
	override void OnDebugSpawn()
	{
		GameInventory inventory = GetInventory();

		inventory.CreateAttachment("IAT_PlayingCard_1h");
		inventory.CreateAttachment("IAT_PlayingCard_2h");
		inventory.CreateAttachment("IAT_PlayingCard_3h");
		inventory.CreateAttachment("IAT_PlayingCard_4h");
		inventory.CreateAttachment("IAT_PlayingCard_5h");
		inventory.CreateAttachment("IAT_PlayingCard_6h");
		inventory.CreateAttachment("IAT_PlayingCard_7h");
		inventory.CreateAttachment("IAT_PlayingCard_8h");
		inventory.CreateAttachment("IAT_PlayingCard_9h");
		inventory.CreateAttachment("IAT_PlayingCard_10h");
		inventory.CreateAttachment("IAT_PlayingCard_11h");
		inventory.CreateAttachment("IAT_PlayingCard_12h");
		inventory.CreateAttachment("IAT_PlayingCard_13h");
		inventory.CreateAttachment("IAT_PlayingCard_1c");
		inventory.CreateAttachment("IAT_PlayingCard_2c");
		inventory.CreateAttachment("IAT_PlayingCard_3c");
		inventory.CreateAttachment("IAT_PlayingCard_4c");
		inventory.CreateAttachment("IAT_PlayingCard_5c");
		inventory.CreateAttachment("IAT_PlayingCard_6c");
		inventory.CreateAttachment("IAT_PlayingCard_7c");
		inventory.CreateAttachment("IAT_PlayingCard_8c");
		inventory.CreateAttachment("IAT_PlayingCard_9c");
		inventory.CreateAttachment("IAT_PlayingCard_10c");
		inventory.CreateAttachment("IAT_PlayingCard_11c");
		inventory.CreateAttachment("IAT_PlayingCard_12c");
		inventory.CreateAttachment("IAT_PlayingCard_13c");
		inventory.CreateAttachment("IAT_PlayingCard_1d");
		inventory.CreateAttachment("IAT_PlayingCard_2d");
		inventory.CreateAttachment("IAT_PlayingCard_3d");
		inventory.CreateAttachment("IAT_PlayingCard_4d");
		inventory.CreateAttachment("IAT_PlayingCard_5d");
		inventory.CreateAttachment("IAT_PlayingCard_6d");
		inventory.CreateAttachment("IAT_PlayingCard_7d");
		inventory.CreateAttachment("IAT_PlayingCard_8d");
		inventory.CreateAttachment("IAT_PlayingCard_9d");
		inventory.CreateAttachment("IAT_PlayingCard_10d");
		inventory.CreateAttachment("IAT_PlayingCard_11d");
		inventory.CreateAttachment("IAT_PlayingCard_12d");
		inventory.CreateAttachment("IAT_PlayingCard_13d");
		inventory.CreateAttachment("IAT_PlayingCard_1s");
		inventory.CreateAttachment("IAT_PlayingCard_2s");
		inventory.CreateAttachment("IAT_PlayingCard_3s");
		inventory.CreateAttachment("IAT_PlayingCard_4s");
		inventory.CreateAttachment("IAT_PlayingCard_5s");
		inventory.CreateAttachment("IAT_PlayingCard_6s");
		inventory.CreateAttachment("IAT_PlayingCard_7s");
		inventory.CreateAttachment("IAT_PlayingCard_8s");
		inventory.CreateAttachment("IAT_PlayingCard_9s");
		inventory.CreateAttachment("IAT_PlayingCard_10s");
		inventory.CreateAttachment("IAT_PlayingCard_11s");
		inventory.CreateAttachment("IAT_PlayingCard_12s");
		inventory.CreateAttachment("IAT_PlayingCard_13s");
		inventory.CreateAttachment("IAT_PlayingCard_1j");
		inventory.CreateAttachment("IAT_PlayingCard_2j");
	}
};
class IAT_CardDeck_Basic extends IAT_CardDeck_Colorbase{};
class IAT_CardDeck_Tarot extends IAT_CardDeck_Colorbase{};

class IAT_PlayingCard_Colorbase extends ItemBase{};

class IAT_PlayingCard_1h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_2h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_3h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_4h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_5h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_6h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_7h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_8h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_9h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_10h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_11h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_12h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_13h extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_1c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_2c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_3c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_4c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_5c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_6c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_7c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_8c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_9c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_10c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_11c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_12c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_13c extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_1d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_2d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_3d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_4d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_5d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_6d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_7d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_8d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_9d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_10d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_11d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_12d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_13d extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_1s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_2s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_3s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_4s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_5s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_6s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_7s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_8s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_9s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_10s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_11s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_12s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_13s extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_1j extends IAT_PlayingCard_Colorbase{};
class IAT_PlayingCard_2j extends IAT_PlayingCard_Colorbase{};