class IAT_BoosterPack_ColorBase extends ItemBase
{
	protected int m_TotalCardsToCreate = 0;
	// ============================================= VANILLA OVERRIDE
	override void SetActions()
	{
		super.SetActions();

		AddAction(IAT_ActionOpenBoosterPack);
	}

	// ============================================= CUSTOM CODE
	void OpenBoosterPack()
	{
		// for each card to make
		for (int i = 0; i < m_TotalCardsToCreate; i++)
		{
			CreateCard(GetRandomCardFromBoosterSet());
		}
	}
	void CreateCard(string cardName)
	{
		EntityAI newCard;
		if (Class.CastTo(newCard, GetGame().CreateObjectEx(cardName, GetPosition(), ECE_SETUP|ECE_PLACE_ON_SURFACE|ECE_NOLIFETIME|ECE_DYNAMIC_PERSISTENCY)))
		{
			// PrintFormat("================================================== CREATED NEW CARD: %1", cardName);
		}
		else
		{
			// PrintFormat("================================================== CANNOT CREATE NEW CARD: %1", cardName);
		}
	}
	string GetRandomCardFromBoosterSet()
	{
		return GetSetCards().GetRandomElement();
	}
	TStringArray GetSetCards()
	{
		return {};
	}

};
class IAT_BoosterPack_PlayingCards extends IAT_BoosterPack_ColorBase
{
	void IAT_BoosterPack_PlayingCards()
	{
		m_TotalCardsToCreate = 8;
	}
	// just randomly pick one of the 54 cards (jokers included)
	override TStringArray GetSetCards()
	{
		return {
			"IAT_PlayingCard_A_H",
			"IAT_PlayingCard_2_H",
			"IAT_PlayingCard_3_H",
			"IAT_PlayingCard_4_H",
			"IAT_PlayingCard_5_H",
			"IAT_PlayingCard_6_H",
			"IAT_PlayingCard_7_H",
			"IAT_PlayingCard_8_H",
			"IAT_PlayingCard_9_H",
			"IAT_PlayingCard_10_H",
			"IAT_PlayingCard_J_H",
			"IAT_PlayingCard_Q_H",
			"IAT_PlayingCard_K_H",
			"IAT_PlayingCard_A_D",
			"IAT_PlayingCard_2_D",
			"IAT_PlayingCard_3_D",
			"IAT_PlayingCard_4_D",
			"IAT_PlayingCard_5_D",
			"IAT_PlayingCard_6_D",
			"IAT_PlayingCard_7_D",
			"IAT_PlayingCard_8_D",
			"IAT_PlayingCard_9_D",
			"IAT_PlayingCard_10_D",
			"IAT_PlayingCard_J_D",
			"IAT_PlayingCard_Q_D",
			"IAT_PlayingCard_K_D",
			"IAT_PlayingCard_A_S",
			"IAT_PlayingCard_2_S",
			"IAT_PlayingCard_3_S",
			"IAT_PlayingCard_4_S",
			"IAT_PlayingCard_5_S",
			"IAT_PlayingCard_6_S",
			"IAT_PlayingCard_7_S",
			"IAT_PlayingCard_8_S",
			"IAT_PlayingCard_9_S",
			"IAT_PlayingCard_10_S",
			"IAT_PlayingCard_J_S",
			"IAT_PlayingCard_Q_S",
			"IAT_PlayingCard_K_S",
			"IAT_PlayingCard_A_C",
			"IAT_PlayingCard_2_C",
			"IAT_PlayingCard_3_C",
			"IAT_PlayingCard_4_C",
			"IAT_PlayingCard_5_C",
			"IAT_PlayingCard_6_C",
			"IAT_PlayingCard_7_C",
			"IAT_PlayingCard_8_C",
			"IAT_PlayingCard_9_C",
			"IAT_PlayingCard_10_C",
			"IAT_PlayingCard_J_C",
			"IAT_PlayingCard_Q_C",
			"IAT_PlayingCard_K_C",
			"IAT_PlayingCard_Joker_1",
			"IAT_PlayingCard_Joker_2",
		};
	}
};
class IAT_BoosterPack_TarotCards extends IAT_BoosterPack_ColorBase
{
	void IAT_BoosterPack_TarotCards()
	{
		m_TotalCardsToCreate = 10;
	}
	// just randomly pick one of the cards
	override TStringArray GetSetCards()
	{
		return {
			"IAT_TarotCard_C_1",
			"IAT_TarotCard_C_2",
			"IAT_TarotCard_C_3",
			"IAT_TarotCard_C_4",
			"IAT_TarotCard_C_5",
			"IAT_TarotCard_C_6",
			"IAT_TarotCard_C_7",
			"IAT_TarotCard_C_8",
			"IAT_TarotCard_C_9",
			"IAT_TarotCard_C_10",
			"IAT_TarotCard_C_11",
			"IAT_TarotCard_C_12",
			"IAT_TarotCard_C_13",
			"IAT_TarotCard_C_14",
			"IAT_TarotCard_W_1",
			"IAT_TarotCard_W_2",
			"IAT_TarotCard_W_3",
			"IAT_TarotCard_W_4",
			"IAT_TarotCard_W_5",
			"IAT_TarotCard_W_6",
			"IAT_TarotCard_W_7",
			"IAT_TarotCard_W_8",
			"IAT_TarotCard_W_9",
			"IAT_TarotCard_W_10",
			"IAT_TarotCard_W_11",
			"IAT_TarotCard_W_12",
			"IAT_TarotCard_W_13",
			"IAT_TarotCard_W_14",
			"IAT_TarotCard_P_1",
			"IAT_TarotCard_P_2",
			"IAT_TarotCard_P_3",
			"IAT_TarotCard_P_4",
			"IAT_TarotCard_P_5",
			"IAT_TarotCard_P_6",
			"IAT_TarotCard_P_7",
			"IAT_TarotCard_P_8",
			"IAT_TarotCard_P_9",
			"IAT_TarotCard_P_10",
			"IAT_TarotCard_P_11",
			"IAT_TarotCard_P_12",
			"IAT_TarotCard_P_13",
			"IAT_TarotCard_P_14",
			"IAT_TarotCard_S_1",
			"IAT_TarotCard_S_2",
			"IAT_TarotCard_S_3",
			"IAT_TarotCard_S_4",
			"IAT_TarotCard_S_5",
			"IAT_TarotCard_S_6",
			"IAT_TarotCard_S_7",
			"IAT_TarotCard_S_8",
			"IAT_TarotCard_S_9",
			"IAT_TarotCard_S_10",
			"IAT_TarotCard_S_11",
			"IAT_TarotCard_S_12",
			"IAT_TarotCard_S_13",
			"IAT_TarotCard_S_14",
			"IAT_TarotCard_MA_1",
			"IAT_TarotCard_MA_2",
			"IAT_TarotCard_MA_3",
			"IAT_TarotCard_MA_4",
			"IAT_TarotCard_MA_5",
			"IAT_TarotCard_MA_6",
			"IAT_TarotCard_MA_7",
			"IAT_TarotCard_MA_8",
			"IAT_TarotCard_MA_9",
			"IAT_TarotCard_MA_10",
			"IAT_TarotCard_MA_11",
			"IAT_TarotCard_MA_12",
			"IAT_TarotCard_MA_13",
			"IAT_TarotCard_MA_14",
		};
	}
};
class IAT_BoosterPack_Collectibles_SRP_BR extends IAT_BoosterPack_ColorBase
{
	void IAT_BoosterPack_Collectibles_SRP_BR()
	{
		m_TotalCardsToCreate = 15;
	}

	override void OpenBoosterPack()
	{
		TStringArray cardsToCreate = CreateBoosterSet();
		// for each card to make
		foreach (string cardName : cardsToCreate)
		{
			CreateCard(cardName);
		}
	}

	// we want some custom logic for these cards
	TStringArray CreateBoosterSet()
	{
		TStringArray booster = new TStringArray();

		float chance = Math.RandomFloat01();
		// 12.5% chance (one in eight) to get mythic
		if (chance < 0.125)
		{
			booster.Insert(GetRareMythics().GetRandomElement());
		}
		else
		{
			booster.Insert(GetRares().GetRandomElement());
		}
		// 3 uncommons
		booster.Insert(GetUncommons().GetRandomElement());
		booster.Insert(GetUncommons().GetRandomElement());
		booster.Insert(GetUncommons().GetRandomElement());

		// 9 commons
		booster.Insert(GetCommons().GetRandomElement());
		booster.Insert(GetCommons().GetRandomElement());
		booster.Insert(GetCommons().GetRandomElement());
		booster.Insert(GetCommons().GetRandomElement());
		booster.Insert(GetCommons().GetRandomElement());
		booster.Insert(GetCommons().GetRandomElement());
		booster.Insert(GetCommons().GetRandomElement());
		booster.Insert(GetCommons().GetRandomElement());
		booster.Insert(GetCommons().GetRandomElement());

		chance = Math.RandomFloat01();
		// 33% chance for a "foil" card otherwise 1 more common
		if (chance < 0.33)
		{
			// foils are just chances at rares or uncommons for now
			chance = Math.RandomFloat01();
			if (chance < 0.001)
			{
				booster.Insert(GetRareMythics().GetRandomElement());
			}
			else if (chance < 0.01)
			{
				booster.Insert(GetRares().GetRandomElement());
			}
			else if (chance < 0.33)
			{
				booster.Insert(GetUncommons().GetRandomElement());
			}
			else
			{
				booster.Insert(GetCommons().GetRandomElement());
			}
		}
		else
		{
			booster.Insert(GetCommons().GetRandomElement());
		}
		// 1 basic land
		booster.Insert(GetBasicLands().GetRandomElement());

		return booster;
	}

	TStringArray GetRares()
	{
		return {
			"IAT_CollectibleCard_SRP_BR_16",
			"IAT_CollectibleCard_SRP_BR_17",
			"IAT_CollectibleCard_SRP_BR_18",
			"IAT_CollectibleCard_SRP_BR_36",
			"IAT_CollectibleCard_SRP_BR_37",
			"IAT_CollectibleCard_SRP_BR_38",
			"IAT_CollectibleCard_SRP_BR_56",
			"IAT_CollectibleCard_SRP_BR_57",
			"IAT_CollectibleCard_SRP_BR_58",
			"IAT_CollectibleCard_SRP_BR_76",
			"IAT_CollectibleCard_SRP_BR_77",
			"IAT_CollectibleCard_SRP_BR_78",
			"IAT_CollectibleCard_SRP_BR_81",
			"IAT_CollectibleCard_SRP_BR_84",
			"IAT_CollectibleCard_SRP_BR_85",
			"IAT_CollectibleCard_SRP_BR_90",
			"IAT_CollectibleCard_SRP_BR_94",
			"IAT_CollectibleCard_SRP_BR_95",
			"IAT_CollectibleCard_SRP_BR_97",
			"IAT_CollectibleCard_SRP_BR_99",
			"IAT_CollectibleCard_SRP_BR_100",
			"IAT_CollectibleCard_SRP_BR_103",
			"IAT_CollectibleCard_SRP_BR_106",
			"IAT_CollectibleCard_SRP_BR_109",
			"IAT_CollectibleCard_SRP_BR_112",
			"IAT_CollectibleCard_SRP_BR_121",
			"IAT_CollectibleCard_SRP_BR_122",
			"IAT_CollectibleCard_SRP_BR_123",
			"IAT_CollectibleCard_SRP_BR_124",
			"IAT_CollectibleCard_SRP_BR_125",
			"IAT_CollectibleCard_SRP_BR_126",
			"IAT_CollectibleCard_SRP_BR_127",
			"IAT_CollectibleCard_SRP_BR_128",
			"IAT_CollectibleCard_SRP_BR_138",
			"IAT_CollectibleCard_SRP_BR_139",
			"IAT_CollectibleCard_SRP_BR_147",
			"IAT_CollectibleCard_SRP_BR_148",
			"IAT_CollectibleCard_SRP_BR_149",
			"IAT_CollectibleCard_SRP_BR_150",
		};
	}
	TStringArray GetRareMythics()
	{
		return {
			"IAT_CollectibleCard_SRP_BR_19",
			"IAT_CollectibleCard_SRP_BR_20",
			"IAT_CollectibleCard_SRP_BR_39",
			"IAT_CollectibleCard_SRP_BR_40",
			"IAT_CollectibleCard_SRP_BR_59",
			"IAT_CollectibleCard_SRP_BR_60",
			"IAT_CollectibleCard_SRP_BR_79",
			"IAT_CollectibleCard_SRP_BR_80",
			"IAT_CollectibleCard_SRP_BR_129",
			"IAT_CollectibleCard_SRP_BR_130",
			"IAT_CollectibleCard_SRP_BR_131",
			"IAT_CollectibleCard_SRP_BR_132",
			"IAT_CollectibleCard_SRP_BR_140",
		};
	}
	TStringArray GetUncommons()
	{
		return {
			"IAT_CollectibleCard_SRP_BR_11",
			"IAT_CollectibleCard_SRP_BR_12",
			"IAT_CollectibleCard_SRP_BR_13",
			"IAT_CollectibleCard_SRP_BR_14",
			"IAT_CollectibleCard_SRP_BR_15",
			"IAT_CollectibleCard_SRP_BR_31",
			"IAT_CollectibleCard_SRP_BR_32",
			"IAT_CollectibleCard_SRP_BR_33",
			"IAT_CollectibleCard_SRP_BR_34",
			"IAT_CollectibleCard_SRP_BR_35",
			"IAT_CollectibleCard_SRP_BR_51",
			"IAT_CollectibleCard_SRP_BR_52",
			"IAT_CollectibleCard_SRP_BR_53",
			"IAT_CollectibleCard_SRP_BR_54",
			"IAT_CollectibleCard_SRP_BR_55",
			"IAT_CollectibleCard_SRP_BR_71",
			"IAT_CollectibleCard_SRP_BR_72",
			"IAT_CollectibleCard_SRP_BR_73",
			"IAT_CollectibleCard_SRP_BR_74",
			"IAT_CollectibleCard_SRP_BR_75",
			"IAT_CollectibleCard_SRP_BR_82",
			"IAT_CollectibleCard_SRP_BR_83",
			"IAT_CollectibleCard_SRP_BR_86",
			"IAT_CollectibleCard_SRP_BR_87",
			"IAT_CollectibleCard_SRP_BR_88",
			"IAT_CollectibleCard_SRP_BR_89",
			"IAT_CollectibleCard_SRP_BR_91",
			"IAT_CollectibleCard_SRP_BR_92",
			"IAT_CollectibleCard_SRP_BR_93",
			"IAT_CollectibleCard_SRP_BR_96",
			"IAT_CollectibleCard_SRP_BR_98",
			"IAT_CollectibleCard_SRP_BR_102",
			"IAT_CollectibleCard_SRP_BR_105",
			"IAT_CollectibleCard_SRP_BR_108",
			"IAT_CollectibleCard_SRP_BR_111",
			"IAT_CollectibleCard_SRP_BR_113",
			"IAT_CollectibleCard_SRP_BR_114",
			"IAT_CollectibleCard_SRP_BR_115",
			"IAT_CollectibleCard_SRP_BR_116",
			"IAT_CollectibleCard_SRP_BR_117",
			"IAT_CollectibleCard_SRP_BR_118",
			"IAT_CollectibleCard_SRP_BR_119",
			"IAT_CollectibleCard_SRP_BR_120",
			"IAT_CollectibleCard_SRP_BR_133",
			"IAT_CollectibleCard_SRP_BR_134",
			"IAT_CollectibleCard_SRP_BR_135",
			"IAT_CollectibleCard_SRP_BR_136",
			"IAT_CollectibleCard_SRP_BR_137",
			"IAT_CollectibleCard_SRP_BR_141",
			"IAT_CollectibleCard_SRP_BR_142",
			"IAT_CollectibleCard_SRP_BR_143",
			"IAT_CollectibleCard_SRP_BR_144",
			"IAT_CollectibleCard_SRP_BR_145",
			"IAT_CollectibleCard_SRP_BR_146",
		};
	}
	TStringArray GetCommons()
	{
		return {
			"IAT_CollectibleCard_SRP_BR_1",
			"IAT_CollectibleCard_SRP_BR_2",
			"IAT_CollectibleCard_SRP_BR_3",
			"IAT_CollectibleCard_SRP_BR_4",
			"IAT_CollectibleCard_SRP_BR_5",
			"IAT_CollectibleCard_SRP_BR_6",
			"IAT_CollectibleCard_SRP_BR_7",
			"IAT_CollectibleCard_SRP_BR_8",
			"IAT_CollectibleCard_SRP_BR_9",
			"IAT_CollectibleCard_SRP_BR_10",
			"IAT_CollectibleCard_SRP_BR_21",
			"IAT_CollectibleCard_SRP_BR_22",
			"IAT_CollectibleCard_SRP_BR_23",
			"IAT_CollectibleCard_SRP_BR_24",
			"IAT_CollectibleCard_SRP_BR_25",
			"IAT_CollectibleCard_SRP_BR_26",
			"IAT_CollectibleCard_SRP_BR_27",
			"IAT_CollectibleCard_SRP_BR_28",
			"IAT_CollectibleCard_SRP_BR_29",
			"IAT_CollectibleCard_SRP_BR_30",
			"IAT_CollectibleCard_SRP_BR_41",
			"IAT_CollectibleCard_SRP_BR_42",
			"IAT_CollectibleCard_SRP_BR_43",
			"IAT_CollectibleCard_SRP_BR_44",
			"IAT_CollectibleCard_SRP_BR_45",
			"IAT_CollectibleCard_SRP_BR_46",
			"IAT_CollectibleCard_SRP_BR_47",
			"IAT_CollectibleCard_SRP_BR_48",
			"IAT_CollectibleCard_SRP_BR_49",
			"IAT_CollectibleCard_SRP_BR_50",
			"IAT_CollectibleCard_SRP_BR_61",
			"IAT_CollectibleCard_SRP_BR_62",
			"IAT_CollectibleCard_SRP_BR_63",
			"IAT_CollectibleCard_SRP_BR_64",
			"IAT_CollectibleCard_SRP_BR_65",
			"IAT_CollectibleCard_SRP_BR_66",
			"IAT_CollectibleCard_SRP_BR_67",
			"IAT_CollectibleCard_SRP_BR_68",
			"IAT_CollectibleCard_SRP_BR_69",
			"IAT_CollectibleCard_SRP_BR_70",
		};
	}
	TStringArray GetBasicLands()
	{
		return {
			"IAT_CollectibleCard_SRP_BR_101",
			"IAT_CollectibleCard_SRP_BR_104",
			"IAT_CollectibleCard_SRP_BR_107",
			"IAT_CollectibleCard_SRP_BR_110",
		};
	}
};
class IAT_BoosterPack_Collectibles_SRP_PL extends IAT_BoosterPack_ColorBase
{
	void IAT_BoosterPack_Collectibles_SRP_PL()
	{
		m_TotalCardsToCreate = 1;
	}
	// just randomly pick one of the 54 cards (jokers included)
	override TStringArray GetSetCards()
	{
		return {
			"IAT_CollectibleCard_SRP_PL_1",
			"IAT_CollectibleCard_SRP_PL_2",
			"IAT_CollectibleCard_SRP_PL_3",
			"IAT_CollectibleCard_SRP_PL_4",
			"IAT_CollectibleCard_SRP_PL_5",
			"IAT_CollectibleCard_SRP_PL_6",
			"IAT_CollectibleCard_SRP_PL_7",
			"IAT_CollectibleCard_SRP_PL_8",
			"IAT_CollectibleCard_SRP_PL_9",
			"IAT_CollectibleCard_SRP_PL_10",
			"IAT_CollectibleCard_SRP_PL_11",
			"IAT_CollectibleCard_SRP_PL_12",
			"IAT_CollectibleCard_SRP_PL_13",
			"IAT_CollectibleCard_SRP_PL_14",
			"IAT_CollectibleCard_SRP_PL_15",
			"IAT_CollectibleCard_SRP_PL_16",
			"IAT_CollectibleCard_SRP_PL_17",
			"IAT_CollectibleCard_SRP_PL_18",
		};
	}
};




class IAT_BoosterPack_VinylRecordArt extends IAT_BoosterPack_ColorBase
{
	void IAT_BoosterPack_VinylRecordArt()
	{
		m_TotalCardsToCreate = 1;
	}
	// just randomly pick one of the 54 cards (jokers included)
	override TStringArray GetSetCards()
	{
		return {
			"IAT_VinylRecordArt_01",
			"IAT_VinylRecordArt_02",
			"IAT_VinylRecordArt_03",
			"IAT_VinylRecordArt_04",
			"IAT_VinylRecordArt_05",
			"IAT_VinylRecordArt_06",
			"IAT_VinylRecordArt_07",
			"IAT_VinylRecordArt_08",
			"IAT_VinylRecordArt_09",
			"IAT_VinylRecordArt_10",
			"IAT_VinylRecordArt_11",
			"IAT_VinylRecordArt_12",
			"IAT_VinylRecordArt_13",
			"IAT_VinylRecordArt_14",
			"IAT_VinylRecordArt_15",
			"IAT_VinylRecordArt_16",
			"IAT_VinylRecordArt_17",
			"IAT_VinylRecordArt_18",
			"IAT_VinylRecordArt_19",
			"IAT_VinylRecordArt_20",
			"IAT_VinylRecordArt_21",
			"IAT_VinylRecordArt_22",
			"IAT_VinylRecordArt_23",
			"IAT_VinylRecordArt_24",
			"IAT_VinylRecordArt_25",
			"IAT_VinylRecordArt_26",
			"IAT_VinylRecordArt_27",
			"IAT_VinylRecordArt_28",
			"IAT_VinylRecordArt_29",
			"IAT_VinylRecordArt_30",
			"IAT_VinylRecordArt_31",
			"IAT_VinylRecordArt_32",
			"IAT_VinylRecordArt_33",
			"IAT_VinylRecordArt_34",
			"IAT_VinylRecordArt_35",
			"IAT_VinylRecordArt_36",
			"IAT_VinylRecordArt_37",
			"IAT_VinylRecordArt_38",
			"IAT_VinylRecordArt_39",
			"IAT_VinylRecordArt_40",
			"IAT_VinylRecordArt_41",
			"IAT_VinylRecordArt_42",
			"IAT_VinylRecordArt_43",
			"IAT_VinylRecordArt_44",
			"IAT_VinylRecordArt_45",
			"IAT_VinylRecordArt_46",
			"IAT_VinylRecordArt_47",
			"IAT_VinylRecordArt_48",
			"IAT_VinylRecordArt_49",
			"IAT_VinylRecordArt_50",
			"IAT_VinylRecordArt_51",
			"IAT_VinylRecordArt_52",
			"IAT_VinylRecordArt_53",
			"IAT_VinylRecordArt_54",
			"IAT_VinylRecordArt_55",
			"IAT_VinylRecordArt_56",
			"IAT_VinylRecordArt_57",
			"IAT_VinylRecordArt_58",
			"IAT_VinylRecordArt_59",
			"IAT_VinylRecordArt_60",
			"IAT_VinylRecordArt_61",
			"IAT_VinylRecordArt_62",
			"IAT_VinylRecordArt_63",
			"IAT_VinylRecordArt_64",
			"IAT_VinylRecordArt_65",
			"IAT_VinylRecordArt_66",
			"IAT_VinylRecordArt_67",
			"IAT_VinylRecordArt_68",
			"IAT_VinylRecordArt_69",
			"IAT_VinylRecordArt_70",
			"IAT_VinylRecordArt_71",
			"IAT_VinylRecordArt_72",
			"IAT_VinylRecordArt_73",
			"IAT_VinylRecordArt_74",
			"IAT_VinylRecordArt_75",
			"IAT_VinylRecordArt_76",
			"IAT_VinylRecordArt_77",
			"IAT_VinylRecordArt_78",
			"IAT_VinylRecordArt_79",
			"IAT_VinylRecordArt_80",
			"IAT_VinylRecordArt_81",
			"IAT_VinylRecordArt_82",
			"IAT_VinylRecordArt_83",
			"IAT_VinylRecordArt_84",
			"IAT_VinylRecordArt_85",
			"IAT_VinylRecordArt_86",
			"IAT_VinylRecordArt_87",
			"IAT_VinylRecordArt_88",
			"IAT_VinylRecordArt_89",
			"IAT_VinylRecordArt_90",
			"IAT_VinylRecordArt_91",
			"IAT_VinylRecordArt_92",
			"IAT_VinylRecordArt_93",
			"IAT_VinylRecordArt_94",
			"IAT_VinylRecordArt_95",
			"IAT_VinylRecordArt_96",
			"IAT_VinylRecordArt_97",
			"IAT_VinylRecordArt_98",
			"IAT_VinylRecordArt_99",
			"IAT_VinylRecordArt_100",
			"IAT_VinylRecordArt_101",
			"IAT_VinylRecordArt_102",
			"IAT_VinylRecordArt_103",
			"IAT_VinylRecordArt_104",
			"IAT_VinylRecordArt_105",
			"IAT_VinylRecordArt_106",
			"IAT_VinylRecordArt_107",
			"IAT_VinylRecordArt_108",
			"IAT_VinylRecordArt_109",
			"IAT_VinylRecordArt_110",
			"IAT_VinylRecordArt_111",
			"IAT_VinylRecordArt_112",
			"IAT_VinylRecordArt_113",
			"IAT_VinylRecordArt_114",
			"IAT_VinylRecordArt_115",
			"IAT_VinylRecordArt_116",
			"IAT_VinylRecordArt_117",
			"IAT_VinylRecordArt_118",
			"IAT_VinylRecordArt_119",
			"IAT_VinylRecordArt_120",
			"IAT_VinylRecordArt_121",
			"IAT_VinylRecordArt_122",
			"IAT_VinylRecordArt_123",
			"IAT_VinylRecordArt_124",
			"IAT_VinylRecordArt_125",
			"IAT_VinylRecordArt_126",
			"IAT_VinylRecordArt_127",
			"IAT_VinylRecordArt_128",
			"IAT_VinylRecordArt_129",
			"IAT_VinylRecordArt_130",
			"IAT_VinylRecordArt_131",
			"IAT_VinylRecordArt_132",
			"IAT_VinylRecordArt_133",
			"IAT_VinylRecordArt_134",
			"IAT_VinylRecordArt_135",
			"IAT_VinylRecordArt_136",
			"IAT_VinylRecordArt_137",
			"IAT_VinylRecordArt_138",
			"IAT_VinylRecordArt_139",
			"IAT_VinylRecordArt_140",
			"IAT_VinylRecordArt_141",
			"IAT_VinylRecordArt_142",
			"IAT_VinylRecordArt_143",
			"IAT_VinylRecordArt_144",
			"IAT_VinylRecordArt_145",
			"IAT_VinylRecordArt_146",
			"IAT_VinylRecordArt_147",
			"IAT_VinylRecordArt_148",
			"IAT_VinylRecordArt_149",
			"IAT_VinylRecordArt_150",
			"IAT_VinylRecordArt_151",
			"IAT_VinylRecordArt_152",
			"IAT_VinylRecordArt_153",
			"IAT_VinylRecordArt_154",
			"IAT_VinylRecordArt_155",
			"IAT_VinylRecordArt_156",
			"IAT_VinylRecordArt_157",
			"IAT_VinylRecordArt_158",
			"IAT_VinylRecordArt_159",
			"IAT_VinylRecordArt_160",
			"IAT_VinylRecordArt_161",
			"IAT_VinylRecordArt_162",
			"IAT_VinylRecordArt_163",
			"IAT_VinylRecordArt_164",
			"IAT_VinylRecordArt_165",
			"IAT_VinylRecordArt_166",
			"IAT_VinylRecordArt_167",
			"IAT_VinylRecordArt_168",
			"IAT_VinylRecordArt_169",
			"IAT_VinylRecordArt_170",
			"IAT_VinylRecordArt_171",
			"IAT_VinylRecordArt_172",
			"IAT_VinylRecordArt_173",
			"IAT_VinylRecordArt_174",
			"IAT_VinylRecordArt_175",
			"IAT_VinylRecordArt_176",
			"IAT_VinylRecordArt_177",
			"IAT_VinylRecordArt_178",
			"IAT_VinylRecordArt_179",
			"IAT_VinylRecordArt_180",
			"IAT_VinylRecordArt_181",
			"IAT_VinylRecordArt_182",
			"IAT_VinylRecordArt_183",
			"IAT_VinylRecordArt_184",
			"IAT_VinylRecordArt_185",
			"IAT_VinylRecordArt_186",
			"IAT_VinylRecordArt_187",
			"IAT_VinylRecordArt_188",
			"IAT_VinylRecordArt_189",
			"IAT_VinylRecordArt_190",
			"IAT_VinylRecordArt_191",
			"IAT_VinylRecordArt_192",
			"IAT_VinylRecordArt_193",
			"IAT_VinylRecordArt_194",
			"IAT_VinylRecordArt_195",
			"IAT_VinylRecordArt_196",
			"IAT_VinylRecordArt_197",
			"IAT_VinylRecordArt_198",
			"IAT_VinylRecordArt_199",
			"IAT_VinylRecordArt_200",
			"IAT_VinylRecordArt_201",
			"IAT_VinylRecordArt_202",
			"IAT_VinylRecordArt_203",
			"IAT_VinylRecordArt_204",
			"IAT_VinylRecordArt_205",
			"IAT_VinylRecordArt_206",
			"IAT_VinylRecordArt_207",
			"IAT_VinylRecordArt_208",
			"IAT_VinylRecordArt_209",
			"IAT_VinylRecordArt_210",
			"IAT_VinylRecordArt_211",
			"IAT_VinylRecordArt_212",
			"IAT_VinylRecordArt_213",
			"IAT_VinylRecordArt_214",
			"IAT_VinylRecordArt_215",
			"IAT_VinylRecordArt_216",
			"IAT_VinylRecordArt_217",
			"IAT_VinylRecordArt_218",
			"IAT_VinylRecordArt_219",
			"IAT_VinylRecordArt_220",
			"IAT_VinylRecordArt_221",
			"IAT_VinylRecordArt_222",
			"IAT_VinylRecordArt_223",
			"IAT_VinylRecordArt_224",
			"IAT_VinylRecordArt_225",
			"IAT_VinylRecordArt_226",
			"IAT_VinylRecordArt_227",
			"IAT_VinylRecordArt_228",
			"IAT_VinylRecordArt_229",
			"IAT_VinylRecordArt_230",
			"IAT_VinylRecordArt_231",
			"IAT_VinylRecordArt_232",
			"IAT_VinylRecordArt_233",
			"IAT_VinylRecordArt_234",
			"IAT_VinylRecordArt_235",
			"IAT_VinylRecordArt_236",
			"IAT_VinylRecordArt_237",
			"IAT_VinylRecordArt_238",
			"IAT_VinylRecordArt_239",
			"IAT_VinylRecordArt_240",
			"IAT_VinylRecordArt_241",
			"IAT_VinylRecordArt_242",
			"IAT_VinylRecordArt_243",
			"IAT_VinylRecordArt_244",
			"IAT_VinylRecordArt_245",
			"IAT_VinylRecordArt_246",
			"IAT_VinylRecordArt_247",
			"IAT_VinylRecordArt_248",
			"IAT_VinylRecordArt_249",
			"IAT_VinylRecordArt_250",
			"IAT_VinylRecordArt_251",
			"IAT_VinylRecordArt_252",
			"IAT_VinylRecordArt_253",
			"IAT_VinylRecordArt_254",
			"IAT_VinylRecordArt_255",
			"IAT_VinylRecordArt_256",
			"IAT_VinylRecordArt_257",
			"IAT_VinylRecordArt_258",
			"IAT_VinylRecordArt_259",
			"IAT_VinylRecordArt_260",
			"IAT_VinylRecordArt_261",
			"IAT_VinylRecordArt_262",
			"IAT_VinylRecordArt_263",
			"IAT_VinylRecordArt_264",
			"IAT_VinylRecordArt_265",
			"IAT_VinylRecordArt_266",
			"IAT_VinylRecordArt_267",
			"IAT_VinylRecordArt_268",
			"IAT_VinylRecordArt_269",
			"IAT_VinylRecordArt_270",
			"IAT_VinylRecordArt_271",
			"IAT_VinylRecordArt_272",
		};
	}
};
class IAT_BoosterPack_VinylCover extends IAT_BoosterPack_ColorBase
{
	void IAT_BoosterPack_VinylCover()
	{
		m_TotalCardsToCreate = 1;
	}
	// just randomly pick one of the 54 cards (jokers included)
	override TStringArray GetSetCards()
	{
		return {
			"IAT_VinylCover_01",
			"IAT_VinylCover_02",
			"IAT_VinylCover_03",
			"IAT_VinylCover_04",
			"IAT_VinylCover_05",
			"IAT_VinylCover_06",
			"IAT_VinylCover_07",
			"IAT_VinylCover_08",
			"IAT_VinylCover_09",
			"IAT_VinylCover_10",
			"IAT_VinylCover_11",
			"IAT_VinylCover_12",
			"IAT_VinylCover_13",
			"IAT_VinylCover_14",
			"IAT_VinylCover_15",
			"IAT_VinylCover_16",
			"IAT_VinylCover_17",
			"IAT_VinylCover_18",
			"IAT_VinylCover_19",
			"IAT_VinylCover_20",
			"IAT_VinylCover_21",
			"IAT_VinylCover_22",
			"IAT_VinylCover_23",
			"IAT_VinylCover_24",
			"IAT_VinylCover_25",
			"IAT_VinylCover_26",
			"IAT_VinylCover_27",
			"IAT_VinylCover_28",
			"IAT_VinylCover_29",
			"IAT_VinylCover_30",
			"IAT_VinylCover_31",
			"IAT_VinylCover_32",
			"IAT_VinylCover_33",
			"IAT_VinylCover_34",
			"IAT_VinylCover_35",
			"IAT_VinylCover_36",
			"IAT_VinylCover_37",
			"IAT_VinylCover_38",
			"IAT_VinylCover_39",
			"IAT_VinylCover_40",
			"IAT_VinylCover_41",
			"IAT_VinylCover_42",
			"IAT_VinylCover_43",
			"IAT_VinylCover_44",
			"IAT_VinylCover_45",
			"IAT_VinylCover_46",
			"IAT_VinylCover_47",
			"IAT_VinylCover_48",
			"IAT_VinylCover_49",
			"IAT_VinylCover_50",
			"IAT_VinylCover_51",
			"IAT_VinylCover_52",
			"IAT_VinylCover_53",
			"IAT_VinylCover_54",
			"IAT_VinylCover_55",
			"IAT_VinylCover_56",
			"IAT_VinylCover_57",
			"IAT_VinylCover_58",
			"IAT_VinylCover_59",
			"IAT_VinylCover_60",
			"IAT_VinylCover_61",
			"IAT_VinylCover_62",
			"IAT_VinylCover_63",
			"IAT_VinylCover_64",
			"IAT_VinylCover_65",
			"IAT_VinylCover_66",
			"IAT_VinylCover_67",
			"IAT_VinylCover_68",
			"IAT_VinylCover_69",
			"IAT_VinylCover_70",
			"IAT_VinylCover_71",
			"IAT_VinylCover_72",
			"IAT_VinylCover_73",
			"IAT_VinylCover_74",
			"IAT_VinylCover_75",
			"IAT_VinylCover_76",
			"IAT_VinylCover_77",
			"IAT_VinylCover_78",
			"IAT_VinylCover_79",
			"IAT_VinylCover_80",
			"IAT_VinylCover_81",
			"IAT_VinylCover_82",
			"IAT_VinylCover_83",
			"IAT_VinylCover_84",
			"IAT_VinylCover_85",
			"IAT_VinylCover_86",
			"IAT_VinylCover_87",
			"IAT_VinylCover_88",
			"IAT_VinylCover_89",
			"IAT_VinylCover_90",
			"IAT_VinylCover_91",
			"IAT_VinylCover_92",
			"IAT_VinylCover_93",
			"IAT_VinylCover_94",
			"IAT_VinylCover_95",
			"IAT_VinylCover_96",
			"IAT_VinylCover_97",
			"IAT_VinylCover_98",
			"IAT_VinylCover_99",
			"IAT_VinylCover_100",
			"IAT_VinylCover_101",
			"IAT_VinylCover_102",
			"IAT_VinylCover_103",
			"IAT_VinylCover_104",
			"IAT_VinylCover_105",
			"IAT_VinylCover_106",
			"IAT_VinylCover_107",
			"IAT_VinylCover_108",
			"IAT_VinylCover_109",
			"IAT_VinylCover_110",
			"IAT_VinylCover_111",
			"IAT_VinylCover_112",
			"IAT_VinylCover_113",
			"IAT_VinylCover_114",
			"IAT_VinylCover_115",
			"IAT_VinylCover_116",
			"IAT_VinylCover_117",
			"IAT_VinylCover_118",
			"IAT_VinylCover_119",
			"IAT_VinylCover_120",
			"IAT_VinylCover_121",
			"IAT_VinylCover_122",
			"IAT_VinylCover_123",
			"IAT_VinylCover_124",
			"IAT_VinylCover_125",
			"IAT_VinylCover_126",
			"IAT_VinylCover_127",
			"IAT_VinylCover_128",
			"IAT_VinylCover_129",
			"IAT_VinylCover_130",
			"IAT_VinylCover_131",
			"IAT_VinylCover_132",
			"IAT_VinylCover_133",
			"IAT_VinylCover_134",
			"IAT_VinylCover_135",
			"IAT_VinylCover_136",
			"IAT_VinylCover_137",
			"IAT_VinylCover_138",
			"IAT_VinylCover_139",
			"IAT_VinylCover_140",
			"IAT_VinylCover_141",
			"IAT_VinylCover_142",
			"IAT_VinylCover_143",
			"IAT_VinylCover_144",
			"IAT_VinylCover_145",
			"IAT_VinylCover_146",
			"IAT_VinylCover_147",
			"IAT_VinylCover_148",
			"IAT_VinylCover_149",
			"IAT_VinylCover_150",
			"IAT_VinylCover_151",
			"IAT_VinylCover_152",
			"IAT_VinylCover_153",
			"IAT_VinylCover_154",
			"IAT_VinylCover_155",
			"IAT_VinylCover_156",
			"IAT_VinylCover_157",
			"IAT_VinylCover_158",
			"IAT_VinylCover_159",
			"IAT_VinylCover_160",
			"IAT_VinylCover_161",
			"IAT_VinylCover_162",
			"IAT_VinylCover_163",
			"IAT_VinylCover_164",
			"IAT_VinylCover_165",
			"IAT_VinylCover_166",
			"IAT_VinylCover_167",
			"IAT_VinylCover_168",
			"IAT_VinylCover_169",
			"IAT_VinylCover_170",
			"IAT_VinylCover_171",
			"IAT_VinylCover_172",
			"IAT_VinylCover_173",
			"IAT_VinylCover_174",
			"IAT_VinylCover_175",
			"IAT_VinylCover_176",
			"IAT_VinylCover_177",
			"IAT_VinylCover_178",
			"IAT_VinylCover_179",
			"IAT_VinylCover_180",
			"IAT_VinylCover_181",
			"IAT_VinylCover_182",
			"IAT_VinylCover_183",
			"IAT_VinylCover_184",
			"IAT_VinylCover_185",
			"IAT_VinylCover_186",
			"IAT_VinylCover_187",
			"IAT_VinylCover_188",
			"IAT_VinylCover_189",
			"IAT_VinylCover_190",
			"IAT_VinylCover_191",
			"IAT_VinylCover_192",
			"IAT_VinylCover_193",
			"IAT_VinylCover_194",
			"IAT_VinylCover_195",
			"IAT_VinylCover_196",
			"IAT_VinylCover_197",
			"IAT_VinylCover_198",
			"IAT_VinylCover_199",
			"IAT_VinylCover_200",
			"IAT_VinylCover_201",
			"IAT_VinylCover_202",
			"IAT_VinylCover_203",
			"IAT_VinylCover_204",
			"IAT_VinylCover_205",
			"IAT_VinylCover_206",
			"IAT_VinylCover_207",
			"IAT_VinylCover_208",
			"IAT_VinylCover_209",
			"IAT_VinylCover_210",
			"IAT_VinylCover_211",
			"IAT_VinylCover_212",
			"IAT_VinylCover_213",
			"IAT_VinylCover_214",
			"IAT_VinylCover_215",
			"IAT_VinylCover_216",
			"IAT_VinylCover_217",
			"IAT_VinylCover_218",
			"IAT_VinylCover_219",
			"IAT_VinylCover_220",
			"IAT_VinylCover_221",
			"IAT_VinylCover_222",
			"IAT_VinylCover_223",
			"IAT_VinylCover_224",
			"IAT_VinylCover_225",
			"IAT_VinylCover_226",
			"IAT_VinylCover_227",
			"IAT_VinylCover_228",
			"IAT_VinylCover_229",
			"IAT_VinylCover_230",
			"IAT_VinylCover_231",
			"IAT_VinylCover_232",
			"IAT_VinylCover_233",
			"IAT_VinylCover_234",
			"IAT_VinylCover_235",
			"IAT_VinylCover_236",
			"IAT_VinylCover_237",
			"IAT_VinylCover_238",
			"IAT_VinylCover_239",
			"IAT_VinylCover_240",
			"IAT_VinylCover_241",
			"IAT_VinylCover_242",
			"IAT_VinylCover_243",
			"IAT_VinylCover_244",
			"IAT_VinylCover_245",
			"IAT_VinylCover_246",
			"IAT_VinylCover_247",
			"IAT_VinylCover_248",
			"IAT_VinylCover_249",
			"IAT_VinylCover_250",
			"IAT_VinylCover_251",
			"IAT_VinylCover_252",
			"IAT_VinylCover_253",
			"IAT_VinylCover_254",
			"IAT_VinylCover_255",
			"IAT_VinylCover_256",
			"IAT_VinylCover_257",
			"IAT_VinylCover_258",
			"IAT_VinylCover_259",
			"IAT_VinylCover_260",
			"IAT_VinylCover_261",
			"IAT_VinylCover_262",
			"IAT_VinylCover_263",
			"IAT_VinylCover_264",
			"IAT_VinylCover_265",
			"IAT_VinylCover_266",
			"IAT_VinylCover_267",
			"IAT_VinylCover_268",
			"IAT_VinylCover_269",
			"IAT_VinylCover_270",
			"IAT_VinylCover_271",
			"IAT_VinylCover_272",
		};
	}
};

class IAT_BoosterPack_PictureFrames extends IAT_BoosterPack_ColorBase
{
	void IAT_BoosterPack_PictureFrames()
	{
		m_TotalCardsToCreate = 1;
	}
	// just randomly pick one of the 54 cards (jokers included)
	override TStringArray GetSetCards()
	{
		return {
			// LANDSCAPE
			"IAT_PictureFrame_Landscape_SaltWoodCastle",
			// PORTRAIT
			"IAT_PictureFrame_Portrait_AliensAttack",
			"IAT_PictureFrame_Portrait_BGroup",
			"IAT_PictureFrame_Portrait_BitterRose",
			"IAT_PictureFrame_Portrait_MilitaryMen",
			"IAT_PictureFrame_Portrait_SettlerWarning",
			"IAT_PictureFrame_Portrait_TheCenturion",
			"IAT_PictureFrame_Portrait_UniverseFighters",
			"IAT_PictureFrame_Portrait_Unsinkable",
			// SQUARE
			"IAT_PictureFrame_Square_RomeSunset"
		};
	}
};
