class IAT_Melee_BerserkSword_ColorBase extends Sword{};
class IAT_Melee_BerserkSword_Basic extends IAT_Melee_BerserkSword_ColorBase{};
class IAT_Melee_BerserkSword_Illusive extends IAT_Melee_BerserkSword_ColorBase{};

class IAT_Melee_FriedesScythe_ColorBase extends Sword{};
class IAT_Melee_FriedesScythe_Basic extends IAT_Melee_FriedesScythe_ColorBase{};
class IAT_Melee_FriedesScythe_theamontiladoraven extends IAT_Melee_FriedesScythe_ColorBase{};