class IAT_Melee_BerserkSword_Colorbase extends Sword{};
class IAT_Melee_BerserkSword_Basic extends IAT_Melee_BerserkSword_Colorbase{};
class IAT_Melee_BerserkSword_Illusive extends IAT_Melee_BerserkSword_Colorbase{};

class IAT_Melee_FriedesScythe_Colorbase extends Sword{};
class IAT_Melee_FriedesScythe_Basic extends IAT_Melee_FriedesScythe_Colorbase{};
class IAT_Melee_FriedesScythe_theamontiladoraven extends IAT_Melee_FriedesScythe_Colorbase{};

class IAT_Melee_GrinningBlade_Colorbase extends Sword{};
class IAT_Melee_GrinningBlade_Basic extends IAT_Melee_GrinningBlade_Colorbase{};
class IAT_Melee_GrinningBlade_itsb14nk extends IAT_Melee_GrinningBlade_Colorbase{};