name: DayZ SRP Sakhal Mods

on:
  push:
    branches:
      - release

jobs:
  dayz_srp_sakhal:
    name: Pack release pbos
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@release

      - name: Change directory
        uses: ./build-tools

      - name: Install Mikero Tools
        uses: arma-actions/mikero-tools@latest

      - name: Change directory
        uses: ./

      - name: pboproject
        run: |
          Get-Command pboproject
          pboproject -P
