name: DayZ SRP Sakhal Mods

on:
  push:
    branches:
      - release

jobs:
  dayz_srp_sakhal:
    name: Pack release pbos
    runs-on: windows-latest
    steps:
      - name: Install Mikero Tools
        uses: arma-actions/mikero-tools@latest

      - name: Checkout
        uses: actions/checkout@v4

      - name: Change directory
        run: cd ${{ github.event.repository.name }}

      - name: Debug
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: pboproject
        run: |
          Get-Command pboproject
          pboproject -P
