name: DayZ SRP Sakhal Mods

on:
  push:
    branches:
    - release/*

jobs:
  dayz_srp_sakhal:
    name: Pack release pbos    
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@release

      - name: Install Mikero Tools
        uses: ./

      # - name: makepbo
      #   run: |
      #     Get-Command makepbo
          
      #     makepbo -P test/addon addon.pbo
      
      # - name: extractpbo
      #   run: |
      #     Get-Command extractpbo

      #     extractpbo -P addon.pbo c:\extracted

      - name: pboproject
        run: |
          Get-Command pboproject
          pboproject -P
