name: DayZ SRP Sakhal Mods

on:
  push:
    branches:
      - release

jobs:
  dayz_srp_sakhal:
    name: Pack release pbos
    runs-on: windows-latest
    steps:
      - name: Install Mikero Tools
        uses: arma-actions/mikero-tools@latest

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: source

      - name: Make mod folders
        run: |
          cd ${{ github.workspace }}
          mkdir mods
          echo ${{ github.workspace }}\source
          echo ${{ github.workspace }}\mods

      - name: Pack Project With PboProject
        run: |
          Get-Command pboproject
          pboProject -P +Z +H +J +Q -E=dayz "${{ github.workspace }}\source" +M=${{ github.workspace }}\mods -X="*.h,*.hpp,*.png,*.cpp,*.txt,thumbs.db,*.dep,*.bak,*.log,*.pew,source,*.tga,*.bat,*.psd,*.cmd,*.mcr,*.fbx,*.max"

      - name: Validate Packing
        run: |
          pwd
          dir
          cd ${{ github.workspace }}\mod
          dir
