name: DayZ SRP Sakhal Mods

on:
  push:
    branches:
      - release

jobs:
  dayz_srp_sakhal:
    name: Pack release pbos
    runs-on: windows-latest
    steps:
      - name: Install Mikero Tools
        uses: arma-actions/mikero-tools@latest

      - name: Make source folders
        run: |
          cd ${{ github.workspace }}
          cd ..
          mkdir source
          mkdir mods
          echo "SOURCE_DIR=$(echo pwd)/source" >> $GITHUB_ENV
          echo "MOD_DIR=$(echo pwd)/mods" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      - name: pboproject
        run: |
          Get-Command pboproject
          pboProject -P +Z +H +J +Q -E=dayz "${{env.SOURCE_DIR}}\${{ github.event.repository.name }}" +M=${{env.MOD_DIR}}\${{ github.event.repository.name }} -X="*.h,*.hpp,*.png,*.cpp,*.txt,thumbs.db,*.dep,*.bak,*.log,*.pew,source,*.tga,*.bat,*.psd,*.cmd,*.mcr,*.fbx,*.max"
