name: DayZ SRP Sakhal Mods

on:
  push:
    branches:
      - release

jobs:
  dayz_srp_sakhal:
    name: Pack release pbos
    runs-on: windows-latest
    env:
      STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
      STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
    steps:
      - name: Setup steam cmd
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Update app
        run: steamcmd +login "$STEAM_USERNAME" "$STEAM_PASSWORD" +app_update 830640 validate +quit

      - name: Install Mikero Tools
        uses: arma-actions/mikero-tools@latest

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: source

      - name: Make mod folders
        run: |
          cd ${{ github.workspace }}
          mkdir mods
          echo ${{ github.workspace }}\source
          echo ${{ github.workspace }}\mods

      - name: Pack Project With PboProject
        run: |
          Get-Command pboproject
          pboProject ${{ github.workspace }}\source +M=${{ github.workspace }}\mods

      - name: Validate Packing
        run: |
          pwd
          cd ${{ github.workspace }}\mods
          pwd
          dir
