name: DayZ SRP Sakhal Mods

on:
  push:
    branches:
      - release

jobs:
  dayz_srp_sakhal:
    name: Pack release pbos
    runs-on: windows-latest
    steps:
      - name: Install Mikero Tools
        uses: arma-actions/mikero-tools@latest

      - name: Make source folders
        run: |
          echo ${{ github.event.repository.name }}
          mkdir source
          mkdir Mods
          pwd
          cd source
          pwd

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      - name: pboproject
        run: |
          Get-Command pboproject
          pboProject -P +Z +H +J +Q -E=dayz "P:\${{ github.event.repository.name }}" +M=P:\Mods\@${{ github.event.repository.name }} -X="*.h,*.hpp,*.png,*.cpp,*.txt,thumbs.db,*.dep,*.bak,*.log,*.pew,source,*.tga,*.bat,*.psd,*.cmd,*.mcr,*.fbx,*.max"
